from odoo import api, fields, models


class ThongTinBaoHanh(models.Model):
    _name = 'thong.tin.bao.hanh'
    id = fields.Char(string="ID")
    nguoi_bao = fields.Char(string="Người báo")
    thong_tin_khach_hang = fields.Text(string="Thông tin khách hàng")
    so_dien_thoai = fields.Char(string="Số điện thoại")
    dia_chi = fields.Text(string="Địa chỉ")
    thong_tin_loi = fields.Text(string="Thông tin lỗi")

    tinh_thanh_id = fields.Many2one('tinh.thanh', string="Tỉnh thành")
    quan_huyen_id = fields.Many2one('quan.huyen', string="Quận/huyện")
    phuong_xa_id = fields.Many2one('phuong.xa', string="Phường/xã")
    loai_san_pham_id = fields.Many2one('loai.san.pham', string="Loại sản phẩm")
    chi_nhanh_id = fields.Many2one('chi.nhanh', string="Chi nhánh")
    # nhan_vien_id = fields.Many2one('nhan.vien', string="Nhân viên")
    # quan_ly_id = fields.Many2one('nguoi.dung', string="Quản lý")
    trang_thai_id = fields.Many2one('trang.thai.bao.hanh', string="Trạng thái")

    #id_ma_loi_tt = fields.Char(string="Email")
    #id_thong_tin_bao_hanh_uq = fields.Char(string="Email")
    #id_ma_don_vi_co_so = fields.Char(string="Email")
    #id_trao_doi_thong_tin = fields.Char(string="Email")
    #id_ma_loi = fields.Char(string="Email")

    dien_thoai_nhan_vien = fields.Char(string="Điện thoại nhân viên")
    so_lan_bao_hanh = fields.Integer(string="Số lần bảo hành")
    ngay_goi = fields.Datetime(string="Ngày gọi", default=fields.Datetime.now)
    ngay_hen = fields.Datetime(string="Ngày hẹn", default=fields.Datetime.now)
    ngay_lap = fields.Datetime(string="Ngày lập", default=fields.Datetime.now)
    ghi_chu = fields.Text(string="Ghi chú")

    #is_sai_cu_phap = fields.Boolean(string="Sai cú pháp")
    #is_update_loi = fields.Boolean(string="Update lỗi")
    #is_kiem_tra_lai = fields.Boolean(string="Kiểm tra lại")
    so_luong = fields.Float(string="Số lượng")
    #is_sms_gui_nhan_vien = fields.Boolean(string="is_sms_gui_nhan_vien")
    #sms_gui_nhan_vien = fields.Text(string="SMS gửi nhân viên")
    #is_sms_gui_sau_bao_hanh = fields.Boolean(string="is_sms_gui_sau_bao_hanh")
    #sms_gui_sau_bao_hanh = fields.Text(string="SMS gửi khách hàng")
    #is_dong = fields.Boolean(string="is_dong")
    #ngay_kh_phan_hoi = fields.Char(string="Ngày khách hàng phản hồi")
    #noi_dung_kh_phan_hoi = fields.Text(string="Nội dung khách hàng phản hồi")
    #cu_phap_web = fields.Text(string="Cú pháp web")
    #ngay_bao_hanh_xong = fields.Date(string="Ngày bảo hành xong")
    #phuong_thuc = fields.Char(string="Phương thức")
    #nguyen_nhan_loi = fields.Text(string="Nguyên nhân lỗi")
    #ten_san_pham = fields.Char(string="Tên sản phẩm")
    #noi_dung_xu_ly = fields.Text(string="Nội dung xử lý")
    #thang = fields.Integer(string="Tháng")
    #nam = fields.Integer(string="Năm")
    #cu_ly = fields.Char(string="Cự ly")
    #tien_dich_vu = fields.Float(string="Tiền dịch vụ")
    #ngay_gui = fields.Date(string="Ngày gửi")
    #ngay_tra_hang = fields.Date(string="Ngày trả hàng")
    #file_path = fields.Text(string="file_path")
